### ISSUE TITLE
[Feature request] Include year by default in paper template

### ISSUE THREAD

**Issue by ltorroba** [lolipopshock/obsidian-scholar#10]
The default paper template is nice, but I think that one thing it is missing is a `year` tag with the year a paper was uploaded/published. Is this tag supported?

Also: It might be useful to document the tags that are supported for the template.

**Comment by lolipopshock** [comment]
Thanks! Good point! The publication time is included in the paper data -- https://github.com/lolipopshock/obsidian-scholar/blob/54568378c814475add59c15c858e5726584ce7f6/src/obsidianScholar.ts#L184 -- and I can change to include the publication year then.

**Comment by lolipopshock** [comment]
Fix in #12
