### ISSUE TITLE
[Feature request] Configure which app is used to open PDFs

### ISSUE THREAD

**Issue by ltorroba** [lolipopshock/obsidian-scholar#11]
I was expecting the "open PDF in system app function" to open PDFs using the _default_ PDF app, but it seems that on Mac it always opens them using Finder. Not sure if this is intended.

I think that the following would be more natural:
1. Open PDF using the default app for opening .pdf files
2. Allow users to configure which app is used to open PDF files (e.g., Acrobat Reader)

**Comment by lolipopshock** [comment]
I am not sure if that helps but could you confirm if Acrobat Reader is your default PDF app following this tutorial? https://kb.mit.edu/confluence/pages/viewpage.action?pageId=3908296

**Comment by ltorroba** [comment]
Yeah, it's currently set to Acrobat. When I click on the PDF via Finder it opens with Acrobat, but using "Open PDF using System app" always does Finder.
<img width="257" alt="image" src="https://github.com/lolipopshock/obsidian-scholar/assets/1550461/4b03a001-31cc-462b-992d-26b27499c274">

Interestingly, if I open the PDF in obsidian and then run "Open in default app", this actually opens Acrobat.

**Comment by lolipopshock** [comment]
Ahh I see.. I can fix it!

**Comment by lolipopshock** [comment]
Fix in #12
